name: IAC GitHub Actions Workflow

# Define este workflow como reutilizable
on:
  workflow_call:
    inputs:
      principal-role-arn:
        type: string
        required: true
        description: 'ARN del rol principal de AWS para autenticación OIDC'
      target-role-arn:
        type: string
        required: true
        description: 'ARN del rol de destino en la cuenta específica del entorno'
      branch-name:
        type: string
        required: true
    # secrets:
    #   required_secret:
    #     required: true

# Los trabajos ejecutan en secuencia por defecto (equivalente a stages en Azure Pipelines)
jobs:
  prerequisites:
    name: 'Prerequisites (CI)'
    runs-on: ubuntu-latest
    steps:
      - name: Debug filesystem
        run: |
          pwd
          ls -la
          ls -la ./templates/
          ls -la .github/workflows/
          ls -la .github/workflows/templates/ || echo "templates directory doesn't exist"
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Corregido: Ruta correcta al template de prerequisites
      - name: Run Prerequisites
        uses: ./.github/workflows/templates/prerequisites/
        # Si el template está en otro repositorio:
        # uses: organization-name/ban-repo-lowcode-2160-bpm-iac_github_actions/.github/workflows/templates/prerequisites@main

  planning:
    name: 'Planning (Validation)'
    runs-on: ubuntu-latest
    needs: prerequisites
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Corregido: Ruta correcta al template de plan_iac
      - name: Plan IAC
        uses: ./.github/workflows/templates/plan_iac/
        # Si el template está en otro repositorio:
        # uses: organization-name/ban-repo-lowcode-2160-bpm-iac_github_actions/.github/workflows/templates/plan_iac@main

  applying:
    name: 'Applying (CD)'
    runs-on: ubuntu-latest
    needs: planning
    # Equivalente a environment en Azure Pipelines
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Corregido: Ruta correcta al template de deploy_iac
      - name: Deploy IAC
        uses: ./.github/workflows/templates/deploy_iac/
        # Si el template está en otro repositorio:
        # uses: organization-name/ban-repo-lowcode-2160-bpm-iac_github_actions/.github/workflows/templates/deploy_iac@main